on: [pull_request, push]

jobs:
  lint_fmt:
    name: cargo fmt
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt
      - name: Check formating
        run: cargo fmt -- --check

  lint_clippy:
    name: Clippy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy
      - name: Install gtk
        run: |
          sudo apt update -yqq
          sudo apt install -yqq --no-install-recommends libgtk-4-dev
      - name: Run clippy
        run: cargo clippy --all-features -- --deny warnings

  tests:
    name: Tests
    strategy:
      matrix:
        mode: ["debug", "release"]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: dtolnay/rust-toolchain@stable

      - name: Install gtk
        run: |
          sudo apt update -yqq
          sudo apt install -yqq --no-install-recommends libgtk-4-dev

      - name: Run tests
        if: matrix.mode == 'debug'
        run: make MODE=debug test

      - name: Run tests (release)
        if: matrix.mode == 'release'
        run: make MODE=release test
